# Generated by Django 4.1.7 on 2023-03-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentator",
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.category"
            ),
        ),
    ]
