# Generated by Django 4.1.7 on 2023-03-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profile's"},
        ),
    ]
